Repository ScribeLabsAI/amazon-trp-node, pull requests merged in 2023-09, with the labels that each got.

#30 chore(master): release 3.0.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#32 Fix tests
  .DS_Store
  .github/release.yml
  .gitignore
  bin/document.ts
  package.json
  tests/UK12640114_2022-06-30.json
  tests/all.test.ts
  tests/doc11.json
  tests/tables/doc11.json
  tests/tsconfig.json
  vitest.config.js
Labels: bug, tests

#33 Add TABLE_FOOTER to zod schema for cell blocks
  src/BlockStruct.ts
Labels: bug

#34 chore(master): release 3.0.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending
